### ISSUE TITLE
Documentation in init.pp is still boilerplate from the module generate skeleton

### ISSUE THREAD

**Issue by igalic** [voxpupuli/puppet-sftp_jail#13]
### What are you seeing

Documentation in init.pp is still boilerplate from the module generate skeleton
### What behaviour did you expect instead

The documentation in init.pp should either match the class parameters, or not exist at all, because README.md covers it.
### Any additional information you'd like to impart

_mumbles something about puppet-strings_

**Comment by nod0n** [comment]
probably it's not perfect, but it's something: #70

**Comment by alexjfisher** [comment]
Thanks @nod0n
