### ISSUE TITLE
concat::fragment error when initing jail 

### ISSUE THREAD

**Issue by gustmoge** [voxpupuli/puppet-sftp_jail#26]
I'm getting this error when following the example:
Error: Failed to apply catalog: Validation of Concat_fragment[match_block hej] failed: Target not set at /etc/puppet_envs/wwwpuppet/modules/concat/manifests/fragment.pp:55 at /etc/puppet_envs/wwwpuppet/modules/concat/manifests/fragment.pp:55

Any ideas?

Could it be: It's calling concat::fragment with "type = > Group," ,  but Group was removed from concat >2.0  ?? 

- Puppet: puppet agent --version
3.7.4
- Module version:
puppet/modules
└─┬ wusa-sftp_jail (v0.1.3)
  └─┬ saz-ssh (v2.9.1)
    ├── puppetlabs-concat (v2.2.0)

## How to reproduce (e.g Puppet code you use)
sftp_jail::jail { 'hej':
  user        => 'hej',
  group       => 'hej',
}

## What are you seeing
[root]# puppet agent   -t  --environment=wwwpuppet
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for server-a.its.uu.se
Error: Failed to apply catalog: Validation of Concat_fragment[match_block hej] failed: Target not set at /etc/puppet_envs/wwwpuppet/modules/concat/manifests/fragment.pp:55 at /etc/puppet_envs/wwwpuppet/modules/concat/manifests/fragment.pp:55
Wrapped exception:
Target not set at /etc/puppet_envs/wwwpuppet/modules/concat/manifests/fragment.pp:55
[root]#

**Comment by domcleal** [comment]
I think you need to `include ::ssh` to use this module, the saz/ssh module must be managing the SSH server configuration for the jail define to work.

**Comment by gustmoge** [comment]
Thnx, it works now!
I didn't want to install saz/ssh since it conflict with our own ssh. But I guess thats life.
Just discovered that scp doesn't work in this environment:
scp  hej@server-a.se:/file file
protocol error: mtime.sec not present 
So I've to figure out if that is a requirement or not.
